import './globals.css'
import { Inter } from 'next/font/google'
import GetNav from './routing'
import { NextAuthProvider } from "./providers";
import { getSession } from "@/services/session"
import { SpeedInsights } from '@vercel/speed-insights/next';

const inter = Inter({
   subsets: ['latin'],
   display: 'swap',
})

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
   const session = await getSession();
   return (
      <html lang="en" className={inter.className}>
         <body>
            <GetNav
               session={session}
            />
            <NextAuthProvider>
               {children}
               <SpeedInsights />
            </NextAuthProvider>
         </body>
      </html>
   )
}